name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.700
    - name: Install dependencies
      working-directory: ./DiffieHellman/Tests/
      run: dotnet restore
    - name: Build
      working-directory: ./DiffieHellman/Tests/
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./DiffieHellman/Tests/
      run: dotnet test --no-restore --verbosity normal
