name: sonarscanner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.700'        
    - run: dotnet --info

    - name: Install sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner
      
    - name: Start sonarscanner
      working-directory: ./DiffieHellman/Tests/
      run: dotnet sonarscanner begin /k:"cho7rose_Exercism" /d:sonar.host.url=https://sonarcloud.io /d:sonar.login="${{ secrets.sonarcloud_login }}" /o:"cho7rose" /d:sonar.verbose=true
    
    - name: Install dependencies
      working-directory: ./DiffieHellman/Tests/
      run: dotnet restore

    - name: Build with sonarscanner
      working-directory: ./DiffieHellman/Tests/    
      run: dotnet build --configuration Release --no-restore ../DiffieHellman.sln -v n
    
    - name: Sonarscanner end
      working-directory: ./DiffieHellman/Tests/
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.sonarcloud_login }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
