# This is a basic workflow to help you get started with Actions

name: sonarscanner

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        version: '2.1.700'
    - run: dotnet --info

    # Runs a single command using the runners shell
    - name: Install sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner
      
    - name: Start sonarscanner
      run: dotnet sonarscanner begin /k:"cho7rose_Exercism" /d:sonar.host.url=https://sonarcloud.io /d:sonar.login="${{ secrets.sonarcloud_login }}" /o:"cho7rose" /d:sonar.verbose=true
    
    - name: Install dependencies
      working-directory: ./DiffieHellman/Tests/
      run: dotnet restore

    - name: Build with sonarscanner
      working-directory: ./DiffieHellman/Tests/    
      run: dotnet build --configuration Release --no-restore ../DiffieHellman.sln -v n
    
    - name: Sonarscanner end 
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.sonarcloud_login }}"
